[package]
name = "blazed-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
bitflags = { version = "2.6.0", features = ["serde"] }
clap = { version = "4.5.20", features = ["derive"] }
crossbeam-channel = "0.5.13"
crossbeam-utils = "0.8.20"
ctrlc = "3.4.5"
env_logger = "0.11.5"
log = "0.4.22"
nalgebra = { version = "0.33.2", features = ["serde-serialize"] }
packet_enum = "0.1.6"
parking_lot = "0.12.3"
serde = { version = "1.0.215", features = ["derive"] }
spin_sleep = "1.2.1"
strum = { version = "0.26.3", features = ["derive"] }
sync_select = "0.1.0"
thiserror = "2.0.3"

[profile.release]
lto = true
codegen-units = 1
