[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
blazed-demo = { path = ".." }
clap = { workspace = true }
crossbeam-channel = { workspace = true }
ctrlc = { workspace = true }
sync_select = { workspace = true }
thiserror = { workspace = true }
